require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VariantsController do

  before do
    # We need an Account in the system
    @account = FactoryGirl.create(:account)
    @product = Product.create!(:name => "Test Product", :id => 1)
  end
  # This should return the minimal set of attributes required to create a valid
  # Variant. As you add validations to Variant, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "product_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VariantsController. Be sure to keep this updated too.
  let(:valid_session) { {current_account_id: @account.id} }

  describe "GET index" do
    it "assigns all variants as @variants" do
      variant = Variant.create! valid_attributes
      get :index, {:product_id => 1}, valid_session
      assigns(:variants).should eq([variant])
    end
  end

  describe "GET show" do
    it "assigns the requested variant as @variant" do
      variant = Variant.create! valid_attributes
      get :show, {:product_id => 1, :id => variant.to_param}, valid_session
      assigns(:variant).should eq(variant)
    end
  end

  describe "GET new" do
    it "assigns a new variant as @variant" do
      get :new, {:product_id => 1}, valid_session
      assigns(:variant).should be_a_new(Variant)
    end
  end

  describe "GET edit" do
    it "assigns the requested variant as @variant" do
      variant = Variant.create! valid_attributes
      get :edit, {:product_id => 1, :id => variant.to_param}, valid_session
      assigns(:variant).should eq(variant)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Variant" do
        expect {
          post :create, {:product_id => 1, :variant => valid_attributes}, valid_session
        }.to change(Variant, :count).by(1)
      end

      it "assigns a newly created variant as @variant" do
        post :create, {:product_id => 1, :variant => valid_attributes}, valid_session
        assigns(:variant).should be_a(Variant)
        assigns(:variant).should be_persisted
      end

      it "redirects to the created variant" do
        post :create, {:product_id => 1, :variant => valid_attributes}, valid_session
        response.should redirect_to([@product, Variant.last])
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved variant as @variant" do
        # Trigger the behavior that occurs when invalid params are submitted
        Variant.any_instance.stub(:save).and_return(false)
        post :create, {:product_id => 1, :variant => { "product_id" => "invalid value" }}, valid_session
        assigns(:variant).should be_a_new(Variant)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Variant.any_instance.stub(:save).and_return(false)
        post :create, {:product_id => 1, :variant => { "product_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested variant" do
        variant = Variant.create! valid_attributes
        # Assuming there are no other variants in the database, this
        # specifies that the Variant created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Variant.any_instance.should_receive(:update).with({ "product_id" => "1" })
        put :update, {:product_id => 1, :id => variant.to_param, :variant => { "product_id" => "1" }}, valid_session
      end

      it "assigns the requested variant as @variant" do
        variant = Variant.create! valid_attributes
        put :update, {:product_id => 1, :id => variant.to_param, :variant => valid_attributes}, valid_session
        assigns(:variant).should eq(variant)
      end

      it "redirects to the variant" do
        variant = Variant.create! valid_attributes
        put :update, {:product_id => 1, :id => variant.to_param, :variant => valid_attributes}, valid_session
        response.should redirect_to([@product, variant])
      end
    end

    describe "with invalid params" do
      it "assigns the variant as @variant" do
        variant = Variant.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Variant.any_instance.stub(:save).and_return(false)
        put :update, {:product_id => 1, :id => variant.to_param, :variant => { "product_id" => "invalid value" }}, valid_session
        assigns(:variant).should eq(variant)
      end

      it "re-renders the 'edit' template" do
        variant = Variant.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Variant.any_instance.stub(:save).and_return(false)
        put :update, {:product_id => 1, :id => variant.to_param, :variant => { "product_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested variant" do
      variant = Variant.create! valid_attributes
      expect {
        delete :destroy, {:product_id => 1, :id => variant.to_param}, valid_session
      }.to change(Variant, :count).by(-1)
    end

    it "redirects to the variants list" do
      variant = Variant.create! valid_attributes
      delete :destroy, {:product_id => 1, :id => variant.to_param}, valid_session
      response.should redirect_to(product_variants_url(@product))
    end
  end

end
